language: python
python:
- '2.7'
- '3.4'
- '3.5'
notifications:
  email: false
install:
# Install binary packages
- travis_retry pip install --upgrade pip setuptools wheel
- travis_retry pip install --only-binary=numpy,scipy numpy scipy
# Install all other dependencies
- travis_retry pip install .
# for tests:
- travis_retry pip install codecov coverage
- pip freeze
script:
- coverage run --source=fcswrite ./setup.py test
- coverage report -m
after_success:
- codecov

