language: python
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
notifications:
  email: false
install:
# Install binary packages
- travis_retry pip install --upgrade pip setuptools wheel
- travis_retry pip install --only-binary=matplotlib,numpy,scipy matplotlib numpy scipy
# Install all other dependencies
- travis_retry pip install .
# for tests:
- travis_retry pip install flake8
- travis_retry pip install codecov coverage
- pip freeze
script:
- set -ev
- coverage run --source=fcswrite setup.py test
- coverage report -m
- codecov
- flake8 fcswrite
- flake8 examples
- flake8 tests
deploy:
  provider: pypi
  user: "ci_zmdd"
  password:
    secure: "mXx6w7gtem5t3Vop2EoVbZ/3tRjTDMavagG9K1IbN2n7a43cT8YxOgTu3KR9jl4rPhw4HbsdoOowIEuBOz4XraEtciwpgUrjikUHt/yufiIk0otEsorU0sH2H3PgARq3gRJ+/HmYwRrflH0e6ouGF/Jhnpsp1nggO6aG9+3/JOzlBE8BxBoSzVjhMf7h9mjMywoMGp89lIGF8gpbkwHg/iE309b8UIxw5F7kLud9A1sdkd6aMlkwjc4/HjOmV+vhJFYzzJyahaHXjgXKmhQXdm4JMT5IdIFufa8Qw2HZ1VtMb1o0m4c8+uWoBHU+FAb+uyT0wHCC9zSowBpt+UdMhebczaG2AFy/2IcE65KeGmpvuo3cfhvg72PXva0U9wQ2l2mCu9iuOHyILTRSvWyOQrAXHPe17tlqbPLsQSvQkazPUmkn+O+hxxQC+kemGMU5z2VcsG87uVdIoyJEPw0ysZPg4/aAGAi6tN3dLI+ZLw0DGBa9DbeH4miiS/t/5Ix9DOZTWHe+hGZvS1/Zr5b2DW5XZRnpx+x1unRkfOWXqYVsedidsCDUog12Rzayg6ZJUKcpws/K3lg39JFVgfHmwwM6+Q1Q9t8CbpvLqnE3lCaQV+PLZz8PF/rztjDrPghTlbS64IwpTDNkedqwCNKU6Ma3YNIvzRCb9kcz6VHNq38="
  on:
    tags: true
    # limit to one version to avoid upload errors
    python: 3.6
  distributions: "sdist bdist_wheel"
